name: Deploy

on:
  push:
    branch:
      - master
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku auth: token
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "atg" #Must be unique in Heroku
          heroku_email: "almirodil@gmail"
          usedocker: true
          remote-branch: "master"


